### ISSUE TITLE
bug with validation of has_calibration

### ISSUE THREAD

**Issue by aclum** [microbiomedata/refscan#26]
this slot uses an any_of range where a string is allowed so nmdc:wfnom-11-0mzdja70.1 for example should not show up as a violoation.

**Comment by aclum** [comment]
These should both be valid:
![image](https://github.com/user-attachments/assets/6deff7f6-263c-45b8-a5ea-c24bb64bed81)
![image](https://github.com/user-attachments/assets/8a7c93a3-d276-4b6f-ada8-bb250e689584)

**Comment by eecavanna** [comment]
I can't read the screenshot 👓 🔦  Do you have a higher contrast version? I'll try switching my GitHub UI to light mode and see if that makes a difference.

**Comment by eecavanna** [comment]
After switching my GitHub UI to light mode, I can see the screenshot OK. All good.

**Comment by eecavanna** [comment]
Here's how I think that slot is defined in `nmdc-schema` version `v11.0.1`:

```yaml
  has_calibration:
    name: has_calibration
    description: a calibration instance associated with a process
    notes:
    - '...'
    from_schema: https://w3id.org/nmdc/nmdc
    any_of:
    - range: CalibrationInformation
    - range: string
```
> Source: [nmdc_materialized_patterns.yaml](https://github.com/microbiomedata/nmdc-schema/blob/65510b8efa1398671392dc98934e98aa3952e541/nmdc_schema/nmdc_materialized_patterns.yaml#L18885-L18897). I redacted the `notes` value to make the snippet more concise.

Refscan ignores ranges that aren't classes.
